### PR TITLE
add features like smart formatting and force changing of number format system

### PR DESCRIPTION
**Pull request by AmanRathoreP**
see docs added in each function for details of the features, or you can use below links too.
- [force number format change overview](https://github.com/AmanRathoreP/format-currency/blob/864d58405b63c8dcf78ca7b09f182d7dde7dc18b/src/format_currency/format.py#L22)
- [smart formatting of numbers overview](https://github.com/AmanRathoreP/format-currency/blob/864d58405b63c8dcf78ca7b09f182d7dde7dc18b/src/format_currency/format.py#L28)
Detailed docs is also added to the code(for new functions).
> Note 2: **Chinese** smart formatting is not added. @arifwn, I would  like your assistance in adding **Chinese** smart formatting as I'm not familiar with it. In any case if you are not able to add it then please open an issue or you can simply comment below(i.e. on the pull request).

Future goal is to add feature to show *2.14x10^6* instead of *2138547* when `none` is provided to kwarg `number_format_system` and `smart_number_formatting` is also set to `True`.

Below provided is an example of the features
image
above cmd output is generated using below code:
```py
from rich.console import Console
from rich.table import Table
from format_currency import format_currency

console = Console()

values = [21545125745458545411, 547131]

for value in values:

    # Create a table
    table = Table(title=f"Currency Format Comparison of value = \"{value}\"")

    # Add columns to the table
    table.add_column("Format Type", justify="center", style="bold")
    table.add_column("EUR (Standard)", justify="right")
    table.add_column("EUR (Smart)", justify="right")
    table.add_column("INR (Standard)", justify="right")
    table.add_column("INR (Smart)", justify="right")
    table.add_column("CN (Standard)", justify="right")
    table.add_column("CN (Smart)", justify="right")

    decimal_places = 2
    # Fill the table with formatted currency values
    for format_type in ["GLObAl", "indian", "Chinese", "aUto", "nonE"]:
        eur_standard = format_currency(value, currency_code='EUR', decimal_places = decimal_places, number_format_system=format_type)
        eur_smart = format_currency(value, currency_code='EUR', decimal_places = decimal_places, number_format_system=format_type, smart_number_formatting = True, place_currency_symbol_at_end = True)
        inr_standard = format_currency(value, currency_code='inr', decimal_places = decimal_places, number_format_system=format_type)
        inr_smart = format_currency(value, currency_code='inr', decimal_places = decimal_places, number_format_system=format_type, smart_number_formatting = True, place_currency_symbol_at_end = True)
        cn_standard = format_currency(value, country_code='CN', decimal_places = decimal_places, number_format_system=format_type)
        cn_smart = format_currency(value, country_code='CN', decimal_places = decimal_places, number_format_system=format_type, smart_number_formatting = True, place_currency_symbol_at_end = True)
        
        if format_type == "aUto":
            row_style = "green"
        elif format_type == "nonE":
            row_style = "red"
        else:
            row_style = None

        table.add_row(f"{format_type.upper()}",
                    f"{eur_standard}", f"{eur_smart}",
                    f"{inr_standard}", f"{inr_smart}",
                    f"{cn_standard}", f"{cn_smart}",
                    style=row_style)

    console.print(table)

```

### CODE REVIEW

**Comment by arifwn** [comment]
I think for China it would be something like this:
```python
units_dict = {
    'only': 1,
    '百': 100,
    '千': 10,
    '万': 10,
    '百万': 100,
    '千万': 10,
    '亿': 10,
    '万亿': 10,
    '千万亿': 1000,
}
```

Also, this will need a new test file (put it under the `tests` directory). No need for some complicated tests for now, just something that covers enough to catch potential regression in the future.

**Comment by AmanRathoreP** [comment]
Tests are added for all possible combinations of kwargs and number system. I'm pretty confident that tests for all number system except Chinese have no issue in them. So, I would like to ask you assistance in reviewing the Chinese number format system tests.

I'm planning to add a special kwarg `use_country_language_for_smart_formatting: bool` this will output **1.12 लाख** instead of **1.12 Lakh** or **32.17 करोड़** instead of **32.17 Crore**. As a native speaker of Hindi language implementing this feature will be no pain for me for Indian number system, but I might find it difficult to implement this feature in Chinese. So, I would like to have your assistance on this once I add this feature for Indian Number System.

For now I believe you can merge this pull request to the arifwn/master. The feature I'm talking above might take some time to be implemented as I also need to work on [Currency Converter](https://github.com/AmanRathoreP/Currency-Converter) etc.
Please provide your thoughts on the feature I talked about.

**Comment by arifwn** [comment]
Thank you Aman. I'm not a chinese speaker too, so I'll probably ask someone to help verifying the chinese number formatting correctness. In the mean time, i'll merge the other changes soon.

**Comment by AmanRathoreP** [comment]
> Thank you Aman. I'm not a chinese speaker too, so I'll probably ask someone to help verifying the chinese number formatting correctness. In the mean time, i'll merge the other changes soon.

Well if that's the case then you can just show them the below table and ask them whether it's correct or not?
| Number Supplied | Smartly Formatted Chinese Number |
| --- | --- |
| 1.68 | 1.68 ¥ |
| 97.67 | 97.67 ¥ |
| 999.89 | 999.89 ¥ |
| 7178.41 | 7178.41 ¥ |
| 89686.03 | 8.97 万 ¥ |
| 307662.72 | 30.77 万 ¥ |
| 8579432.88 | 8.58 百万 ¥ |
| 70457100.06 | 7.05 千万 ¥ |
| 986256196.44 | 9.86 亿 ¥ |
| 1044444788.31 | 1.04 万亿 ¥ |
| 64846241676.00 | 64.85 万亿 ¥ |
| 535875416792.75 | 535.88 万亿 ¥ |
| 9500254573835.82 | 9.50 千万亿 ¥ |

**Comment by arifwn** [comment]
@AmanRathoreP  Here is a feedback from a Chinese-speaking user:

| Number Supplied | Smartly Formatted Chinese Number | Correction |
| --------------- | -------------------------------- | ---------- |
| 1.68 | 1.68 ¥ | ¥1.68 |
| 97.67 | 97.67 ¥ | ¥97.67 |
| 999.89 | 999.89 ¥ | ¥999.89 |
| 7178.41 | 7178.41 ¥ | ¥7178.41 |
| 89686.03 | 8.97 万 ¥ | ¥8.97 万 |
| 307662.72 | 30.77 万 ¥ | ¥30.8万 |
| 8579432.88 | 8.58 百万 ¥ | ¥857.9万 |
| 70457100.06 | 7.05 千万 ¥ | ¥7045.7万 |
| 986256196.44 | 9.86 亿 ¥ | ¥9.9亿 |
| 1044444788.31 | 1.04 万亿 ¥ | ¥10.4亿 |
| 64846241676 | 64.85 万亿 ¥ | ¥648亿 |
| 535875416792.75 | 535.88 万亿 ¥ | ¥5.4千亿 |
| 9500254573835.82 | 9.50 千万亿 ¥ | ¥9.5万亿 |

Seems to be getting complicated. E.g. instead of typing 8.58 百万 , they seems to prefer it as 857.9万 . Same with 7.05 千万, 1.04 万亿, 535.88 万亿. For  9.50 千万亿, it seems we got it wrong, it should be 9.5万亿.

**Comment by AmanRathoreP** [comment]
Thanks for providing **Correction** values I'll make sure to update the code today itself according to the **Correction** values.

**Comment by AmanRathoreP** [comment]
These were the results after updating to modern Chinese standard
| Number Supplied | Smartly Formatted Chinese Number | Values According to Modern Standards|
| --- | --- | --- |
| 1.68 | ¥ 1.68 | ¥ 1.68 |
| 97.67 | ¥ 97.67 | ¥ 97.67 |
| 999.89 | ¥ 999.89 | ¥ 999.89 |
| 7178.41 | ¥ 7178.41 | ¥ 7178.41 |
| 89686.03 | ¥ 8.97 万 | ¥ 8.97 万 |
| 307662.72 | ¥ 30.77 万 | ¥ 30.77 万 |
| 8579432.88 | ¥ 857.94 万 | ¥ 857.94 万 |
| 70457100.06 | ¥ 7045.71 万 | ¥ 7045.71 万 |
| 986256196.44 | ¥ 9.86 亿 | ¥ 9.86 亿 |
| 1044444788.31 | ¥ 10.44 亿 | ¥ 10.44 亿 |
| 64846241676.00 | ¥ 648.46 亿 | ¥ 648.46 亿 |
| 535875416792.75 | ¥ 5.36 千亿 | ¥ 5.36 千亿 |
| 9500254573835.82 | ¥ 9.50 万亿 | ¥ 9.50 万亿 |

above table is generated using below code:
```py
from format_currency import format_currency

values = [1.68, 97.67, 999.89, 7178.41, 89686.03, 307662.72, 8579432.88, 70457100.06, 986256196.44, 1044444788.31, 64846241676, 535875416792.75, 9500254573835.82]
correct_values = ['¥ 1.68', '¥ 97.67', '¥ 999.89', '¥ 7178.41', '¥ 8.97 万', '¥ 30.77 万', '¥ 857.94 万', '¥ 7045.71 万', '¥ 9.86 亿', '¥ 10.44 亿', '¥ 648.46 亿', '¥ 5.36 千亿', '¥ 9.50 万亿']

# Initialize a list to hold the markdown table rows
markdown_table = ["| Number Supplied | Smartly Formatted Chinese Number | Values According to Modern Standards |", "| --- | --- | --- |"]

decimal_places = 2

for value, correct_value in zip(values, correct_values):
    # Format the value in Chinese smart format
    cn_smart = format_currency(value, country_code='CN', decimal_places=decimal_places, number_format_system='Chinese', smart_number_formatting=True)
    
    # Append the formatted value to the markdown table
    markdown_table.append(f"| {value:.2f} | {cn_smart} | {correct_value} |")

# Join the markdown table rows into a single string
markdown_table_str = "\n".join(markdown_table)

# Print the markdown table
with open("dist/te.md", 'w', encoding="utf-8") as f:
    f.write(markdown_table_str)
```

**Comment by arifwn** [comment]
Thank you Aman! I have merged this pull requests.

**Pull request merged**
